# Generated by Django 2.0.1 on 2018-01-18 09:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lamp_control', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Log',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('hostname', models.CharField(max_length=256)),
                ('description', models.TextField()),
                ('lamp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lamp_control.Lamp')),
            ],
        ),
    ]
