# Generated by Django 2.0.1 on 2018-01-19 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lamp_control', '0002_log'),
    ]

    operations = [
        migrations.AddField(
            model_name='lamp',
            name='gpiopin',
            field=models.IntegerField(default=0),
        ),
    ]
